<a href="https://colab.research.google.com/github/subinmun1997/Deep-Learning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
theta = np.array([[4],[3]])
theta

array([[4],
       [3]])

In [3]:
x_i1 = np.array([[1],[0]])
x_i2 = np.array([[1],[1]])

In [4]:
x_i1.T

array([[1, 0]])

In [5]:
x_i1.T.flatten()

array([1, 0])

In [6]:
x_i1

array([[1],
       [0]])

In [7]:
X = np.array([x_i1.T.flatten(),x_i2.T.flatten()])

In [8]:
X

array([[1, 0],
       [1, 1]])

In [9]:
theta.T

array([[4, 3]])

In [10]:
x_i1

array([[1],
       [0]])

In [12]:
y_i1 = theta.T.dot(x_i1)
y_i1

array([[4]])

In [13]:
Y = X.dot(theta)
Y

array([[4],
       [7]])