<a href="https://colab.research.google.com/github/subinmun1997/Deep-Learning/blob/main/numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
X = 2*np.random.rand(4,1)
X

array([[1.67168644],
       [1.07647443],
       [1.64050001],
       [1.58058617]])

In [5]:
b = np.ones((4,1))
b

array([[1.],
       [1.],
       [1.],
       [1.]])

In [6]:
X_b = np.c_[b,X]
X_b

array([[1.        , 1.67168644],
       [1.        , 1.07647443],
       [1.        , 1.64050001],
       [1.        , 1.58058617]])